name: Markdown Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  markdown-basic-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check markdown files exist
        run: |
          set -e
          find . -name "*.md" -not -path "./.git/*" -print
